-- ─────────────────────────────────────────────────────────────
-- 03_database_schemas.sql
-- Run as SYSADMIN
-- ─────────────────────────────────────────────────────────────

USE ROLE SYSADMIN;

-- ── Database ────────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS STOCK_ANALYTICS_DB
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Real-time stock analytics data warehouse';

-- ── Schemas ─────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS STOCK_ANALYTICS_DB.RAW
    COMMENT = 'Landing zone: raw JSON ingested via Snowpipe from S3';

CREATE SCHEMA IF NOT EXISTS STOCK_ANALYTICS_DB.STAGING
    COMMENT = 'dbt staging layer: typed and deduplicated raw data (views)';

CREATE SCHEMA IF NOT EXISTS STOCK_ANALYTICS_DB.INTERMEDIATE
    COMMENT = 'dbt intermediate layer: aggregated metrics (tables)';

CREATE SCHEMA IF NOT EXISTS STOCK_ANALYTICS_DB.MARTS
    COMMENT = 'dbt mart layer: business-facing fact and dimension tables';

CREATE SCHEMA IF NOT EXISTS STOCK_ANALYTICS_DB.SEEDS
    COMMENT = 'dbt seeds: reference / lookup data loaded from CSV files';

-- ── Grants ──────────────────────────────────────────────────
GRANT USAGE ON DATABASE STOCK_ANALYTICS_DB
    TO ROLE STOCK_ANALYTICS_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE PIPE
    ON SCHEMA STOCK_ANALYTICS_DB.RAW
    TO ROLE STOCK_ANALYTICS_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA STOCK_ANALYTICS_DB.STAGING
    TO ROLE STOCK_ANALYTICS_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA STOCK_ANALYTICS_DB.INTERMEDIATE
    TO ROLE STOCK_ANALYTICS_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA STOCK_ANALYTICS_DB.MARTS
    TO ROLE STOCK_ANALYTICS_ROLE;

GRANT USAGE, CREATE TABLE
    ON SCHEMA STOCK_ANALYTICS_DB.SEEDS
    TO ROLE STOCK_ANALYTICS_ROLE;

-- Read-only role gets SELECT on marts only
GRANT USAGE ON DATABASE STOCK_ANALYTICS_DB
    TO ROLE STOCK_ANALYTICS_READ_ROLE;

GRANT USAGE ON SCHEMA STOCK_ANALYTICS_DB.MARTS
    TO ROLE STOCK_ANALYTICS_READ_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA STOCK_ANALYTICS_DB.MARTS
    TO ROLE STOCK_ANALYTICS_READ_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA STOCK_ANALYTICS_DB.MARTS
    TO ROLE STOCK_ANALYTICS_READ_ROLE;
