-- ─────────────────────────────────────────────────────────────
-- 07_grants.sql
-- Run as ACCOUNTADMIN  (or SECURITYADMIN)
-- Final permissions sweep — run after all objects are created
-- ─────────────────────────────────────────────────────────────

USE ROLE ACCOUNTADMIN;

-- Warehouse
GRANT USAGE ON WAREHOUSE STOCK_ANALYTICS_WH
    TO ROLE STOCK_ANALYTICS_ROLE;

-- Database
GRANT USAGE ON DATABASE STOCK_ANALYTICS_DB
    TO ROLE STOCK_ANALYTICS_ROLE;

-- All current and future schemas
GRANT USAGE ON ALL SCHEMAS IN DATABASE STOCK_ANALYTICS_DB
    TO ROLE STOCK_ANALYTICS_ROLE;

GRANT USAGE ON FUTURE SCHEMAS IN DATABASE STOCK_ANALYTICS_DB
    TO ROLE STOCK_ANALYTICS_ROLE;

-- All current and future tables
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE STOCK_ANALYTICS_DB
    TO ROLE STOCK_ANALYTICS_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE STOCK_ANALYTICS_DB
    TO ROLE STOCK_ANALYTICS_ROLE;

-- All current and future views
GRANT SELECT ON ALL VIEWS IN DATABASE STOCK_ANALYTICS_DB
    TO ROLE STOCK_ANALYTICS_ROLE;

GRANT SELECT ON FUTURE VIEWS IN DATABASE STOCK_ANALYTICS_DB
    TO ROLE STOCK_ANALYTICS_ROLE;

-- Stage and pipe access
GRANT READ, WRITE ON STAGE STOCK_ANALYTICS_DB.RAW.S3_TRADES_STAGE
    TO ROLE STOCK_ANALYTICS_ROLE;

GRANT MONITOR, OPERATE ON PIPE STOCK_ANALYTICS_DB.RAW.TRADES_PIPE
    TO ROLE STOCK_ANALYTICS_ROLE;
