/// Company dimension table containing stock metadata. Links to fact tables via SYMBOL.
table dim_companies
	lineageTag: 4e403a14-af18-4005-8329-7699c84369dd

	/// Stock ticker symbol (e.g., AAPL, MSFT). Primary key for joining to fact tables.
	column SYMBOL
		dataType: string
		lineageTag: 374f024b-3b65-4d67-969d-82a9d297aa79
		summarizeBy: none
		sourceColumn: SYMBOL

		annotation SummarizationSetBy = Automatic

	/// Full legal company name (e.g., Apple Inc., Microsoft Corporation).
	column COMPANY_NAME
		dataType: string
		lineageTag: 514a7314-da54-446f-8633-22f88e12d925
		summarizeBy: none
		sourceColumn: COMPANY_NAME

		annotation SummarizationSetBy = Automatic

	/// Stock exchange where the security trades (NASDAQ or NYSE).
	column EXCHANGE
		dataType: string
		lineageTag: 7c2a0cd7-c075-4ca1-988f-935fb866dd55
		summarizeBy: none
		sourceColumn: EXCHANGE

		annotation SummarizationSetBy = Automatic

	/// URL to company logo image. Used for visual display in reports.
	column LOGO_URL
		dataType: string
		lineageTag: 385768ff-1263-43d4-8c1c-3b736c629ada
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: LOGO_URL

		annotation SummarizationSetBy = Automatic

	column SECTOR
		dataType: string
		lineageTag: 0f5457ec-9992-45a0-9a44-a98f59cd5223
		summarizeBy: none
		sourceColumn: SECTOR

		annotation SummarizationSetBy = Automatic

	column INDUSTRY
		dataType: string
		lineageTag: bca7402d-04be-4981-a221-2c43a948b059
		summarizeBy: none
		sourceColumn: INDUSTRY

		annotation SummarizationSetBy = Automatic

	partition dim_companies = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("JDGAEPV-LHA81787.snowflakecomputing.com","STOCK_ANALYTICS_WH",[Implementation="1.0"]),
				    STOCK_ANALYTICS_DB_Database = Source{[Name="STOCK_ANALYTICS_DB",Kind="Database"]}[Data],
				    MARTS_Schema = STOCK_ANALYTICS_DB_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    DIM_COMPANIES_Table = MARTS_Schema{[Name="DIM_COMPANIES",Kind="Table"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(DIM_COMPANIES_Table,{"SYMBOL", "COMPANY_NAME", "SECTOR", "INDUSTRY", "EXCHANGE", "LOGO_URL"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

