/// Hourly OHLCV fact table aggregating trade data into candlestick format. Grain: one row per (symbol, hour).
table fct_stock_ohlcv_hourly
	lineageTag: 0e3171df-aa5a-49a2-8983-c2109231007c

	/// Stock ticker symbol. Foreign key to dim_companies.
	column SYMBOL
		dataType: string
		lineageTag: 13c7c7e0-cd74-4c16-b52a-cdc70a5b8c83
		summarizeBy: none
		sourceColumn: SYMBOL

		annotation SummarizationSetBy = Automatic

	/// First trade price within the hour. Used for candlestick open.
	column OPEN_PRICE
		dataType: double
		lineageTag: 02103a5c-3136-4b55-8fa3-7a61d89c03c8
		summarizeBy: sum
		sourceColumn: OPEN_PRICE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Maximum trade price within the hour. Upper wick of candlestick.
	column HIGH_PRICE
		dataType: double
		lineageTag: 1809f490-f9f2-454a-944a-fbe3af2c7b14
		summarizeBy: sum
		sourceColumn: HIGH_PRICE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Minimum trade price within the hour. Lower wick of candlestick.
	column LOW_PRICE
		dataType: double
		lineageTag: be95c611-aee3-4b6b-8e4f-59c7f8f68d81
		summarizeBy: sum
		sourceColumn: LOW_PRICE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last trade price within the hour. Used for candlestick close and VWAP comparison.
	column CLOSE_PRICE
		dataType: double
		lineageTag: f1bda740-ddb3-4f3c-92df-1a9e9c1bf2ed
		summarizeBy: sum
		sourceColumn: CLOSE_PRICE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Total shares traded within the hour. Key metric for volume spike analysis.
	column TOTAL_VOLUME
		dataType: double
		lineageTag: ca6dfb52-9f6f-4b95-9277-cce21ea5b5f4
		summarizeBy: sum
		sourceColumn: TOTAL_VOLUME

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of individual trades within the hour. Indicates market participation level.
	column TRADE_COUNT
		dataType: double
		lineageTag: 3ed49e2a-038c-4734-b37e-028780431693
		summarizeBy: sum
		sourceColumn: TRADE_COUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Volume-Weighted Average Price. Institutional benchmark for execution quality.
	column VWAP
		dataType: double
		lineageTag: b321f0a2-c155-443c-97ea-c40d18134453
		summarizeBy: sum
		sourceColumn: VWAP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Standard deviation of trade prices within the hour. Primary volatility metric.
	column STDDEV_PRICE
		dataType: double
		lineageTag: 0d560c83-b8e7-4193-8f83-9d7843bea5d2
		summarizeBy: sum
		sourceColumn: STDDEV_PRICE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// High minus Low price (intraday range). Alternative volatility measure.
	column PRICE_RANGE
		dataType: double
		lineageTag: 3a665413-425d-47af-9a58-8650019c5de3
		summarizeBy: sum
		sourceColumn: PRICE_RANGE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Percentage price change (close vs open). Key metric for momentum and correlation analysis.
	column PCT_CHANGE
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a29bd5ef-18be-4997-8ecf-b4ed8153a0a2
		summarizeBy: average
		sourceColumn: PCT_CHANGE

		annotation SummarizationSetBy = User

	/// Calendar date of trading (US/Eastern timezone).
	column TRADED_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: d7006fea-e1b3-48df-987e-b7d53ff9d995
		summarizeBy: none
		sourceColumn: TRADED_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Hour of day (9 AM - 4 PM ET market hours). Use for intraday heatmaps.
	column TRADED_HOUR
		dataType: dateTime
		formatString: Short Time
		lineageTag: c52fd6d5-7621-4c29-a9b6-aff96a3e928d
		summarizeBy: none
		sourceColumn: TRADED_HOUR

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	/// Integer date key (YYYYMMDD format). Foreign key to dim_date.
	column DATE_KEY
		dataType: double
		lineageTag: a67c361b-f0e4-406a-874a-0da1df3c990e
		summarizeBy: none
		sourceColumn: DATE_KEY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fct_stock_ohlcv_hourly = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("JDGAEPV-LHA81787.snowflakecomputing.com","STOCK_ANALYTICS_WH",[Implementation="1.0"]),
				    STOCK_ANALYTICS_DB_Database = Source{[Name="STOCK_ANALYTICS_DB",Kind="Database"]}[Data],
				    MARTS_Schema = STOCK_ANALYTICS_DB_Database{[Name="MARTS",Kind="Schema"]}[Data],
				    FCT_STOCK_OHLCV_HOURLY_Table = MARTS_Schema{[Name="FCT_STOCK_OHLCV_HOURLY",Kind="Table"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(FCT_STOCK_OHLCV_HOURLY_Table,{"SYMBOL", "TRADED_DATE", "TRADED_HOUR", "OPEN_PRICE", "HIGH_PRICE", "LOW_PRICE", "CLOSE_PRICE", "TOTAL_VOLUME", "TRADE_COUNT", "VWAP", "STDDEV_PRICE", "PRICE_RANGE", "PCT_CHANGE", "DATE_KEY"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

